### PR TITLE
Implement a command mode and use it for chroot

### PR DESCRIPTION
**Pull request by bitstreamout**
the current only known command is root=<new_root> which enforce
an already running haveged to switch by using chroot(2) to new
root file system and to an execv(3) there to become rebased.

This allows haveged to survive the switch root within initrd
and hold the entropy at high level.

Signed-off-by: Werner Fink <werner@suse.de>

### CODE REVIEW

**Comment by jirka-h** [comment]
Hallo Werner,

my only concern is about using

#define _GNU_SOURCE

I'm afraid that it can negatively influence the portability of haveged. 

It seems that it's needed only at two locations:

haveged.c:340:19: warning: implicit declaration of function ‘asprintf’; did you mean ‘vsprintf’? [-Wimplicit-function-declaration]
             ret = asprintf(&message, "%c\002%c%s%n", cmd[0], (int)(strlen(root) + 1), root, &len);
                   ^~~~~~~~
                   vsprintf
haveged.c: In function ‘run_daemon’:
haveged.c:596:20: warning: implicit declaration of function ‘accept4’; did you mean ‘accept’? [-Wimplicit-function-declaration]
          conn_fd = accept4(socket_fd, NULL, NULL, SOCK_CLOEXEC|SOCK_NONBLOCK);
                    ^~~~~~~
                    accept

asprintf can be easily replaced with snprintf But I'm not quite sure about the accept4 - could we replace it with accept followed by fcntl(socket, F_SETFL, O_NONBLOCK); ?

See https://stackoverflow.com/questions/12861956/is-it-possible-and-safe-to-make-an-accepting-socket-non-blocking

Thanks
Jirka

**Comment by bitstreamout** [comment]
On Mon, Jul 23, 2018 at 01:11:50AM -0700, jirka-h wrote:
> Hallo Werner,
> 
> my only concern is about using
> 
> #define _GNU_SOURCE
> 
> I'm afraid that it can negatively influence the portability of haveged. 
> 
> It seems that it's needed only at two locations:
> 
> haveged.c:340:19: warning: implicit declaration of function ‘asprintf’; did you mean ‘vsprintf’? [-Wimplicit-function-declaration]
>              ret = asprintf(&message, "%c\002%c%s%n", cmd[0], (int)(strlen(root) + 1), root, &len);
>                    ^~~~~~~~
>                    vsprintf
> haveged.c: In function ‘run_daemon’:
> haveged.c:596:20: warning: implicit declaration of function ‘accept4’; did you mean ‘accept’? [-Wimplicit-function-declaration]
>           conn_fd = accept4(socket_fd, NULL, NULL, SOCK_CLOEXEC|SOCK_NONBLOCK);
>                     ^~~~~~~
>                     accept
> 
> asprintf can be easily replaced with snprintf But I'm not quite sure about the accept4 - could we replace it with accept followed by fcntl(socket, F_SETFL, O_NONBLOCK); ?
> 
> See https://stackoverflow.com/questions/12861956/is-it-possible-and-safe-to-make-an-accepting-socket-non-blocking

Hmmm ... do we have at least C99 aka POSIX.1-2001 (that is glibc newer than
2.0.6)?  With this it would be possible to use

     int size = snprintf(NULL, 0, "%c\002%c%s", cmd[0], (int)(strlen(root) + 1), root);
     if (size >= 0 && size < INT_MAX)
        message = malloc(size);
     else
        error_exit(.....);

or do we really have to support old glibc 2.0.6 and below as well as non glibc
systems or non C99? Also a large but static buffer might be an option and would
also avoid the small leak.

The accept4() can be replaced by something like

     conn_fd = accept4(socket_fd, NULL, NULL);
     if (conn_fd >= 0) {
        int flags = fcntl(conn_fd, F_GETFD, NULL);
        if (flags >= 0)
           fcntl(conn_fd, F_SETFD, O_CLOEXEC);
        flags = fcntl(conn_fd, F_GETFL, NULL);
        if (flags >= 0)
           fcntl(conn_fd, F_SETFL, O_NONBLOCK);
        }

But even BSD based systems should know about accept4(2)

Werner

-- 
  "Having a smoking section in a restaurant is like having
          a peeing section in a swimming pool." -- Edward Burr

**Comment by bitstreamout** [comment]
Now after some porting this might compile even without _GNU_SOURCE and even if accept4(2) and struct ucred are not known

**Comment by jirka-h** [comment]
Hallo Werner,

I'm sorry, it's the holiday season and I have been offline for several days. 

> Now after some porting this might compile even without _GNU_SOURCE and even if accept4(2) and struct ucred are not known

This sounds great! Could you please push it into the initrd branch in your project (bitstreamout/haveged)? 

Thanks
Jirka

**Comment by bitstreamout** [comment]
Hi Jirka,

I've already rebased my branch "initrd" and the pull request is now with the commit  https://github.com/jirka-h/haveged/pull/1/commits/a2496c5de9af7e3ac3ef82a2257d14d8a0ac37fb

**Comment by jirka-h** [comment]
I'm sorry I have missed it. 

I have reviewed it and tested it with

autoreconf -f -i
./configure --prefix=/tmp
make
make install
/tmp/sbin/haveged -n 0 | cat -A

and it looks great. I will bump the version and I will merge it.

Thanks!
Jirka

**Comment by jirka-h** [comment]
Release 1.9.3 is out - could you please test it?

Danke!
Jirka

**Comment by bitstreamout** [comment]
On Fri, Aug 10, 2018 at 05:21:31AM -0700, jirka-h wrote:
> Hallo Werner,
> 
> I'm testing haveged 1.9.3 (with your patch) in the foreground mode, writing random data to stdout:
> 
> haveged -n0 -v3 | PractRand-092-Patched/RNG_test stdin32 -tlmax 512G  -tlfail
> 
> I have noticed it has opened a command mode socket and I wanted to test it. 
> haveged: listening socket at 3
> 
> I can see the socket being opened:
> ```
> ss -a | grep have
> u_str            LISTEN                 1                   128                                                                           @/sys/entropy/haveged 3118834                                                   * 0 
> ```
> 
> I can send a command to it:
> /tmp/A/sbin/haveged -c root=/tmp
> 
> However it seems it has no effect on root directory for the process:
> 
> ```
> $readlink -e /proc/6453/root/
> /
> $/tmp/A/sbin/haveged -c root=/tmp
> $readlink -e /proc/6453/root/
> /
> ```
> Shouldn't be the new root directory /tmp? Am I missing something? 
> 
> BTW, starting the second instance of haveged 
> 
> haveged -n0 -v3 | PractRand-092-Patched/RNG_test stdin32 -tlmax 512G  -tlfail
> 
> reports that it's listening at socket "-2" 
> 
> haveged: listening socket at -2
> 
> which in fact indicates that socket could not be created - it seems something is not right, it should be reported as warning. Could you please have a look what's wrong?
> 
> Thanks!
> Jirka

Below the new root there has to exist a (/tmp)/usr/sbin/haveged as well as there should
be an /etc/initrd-release to enforce the `@' symbol/character at the first byte of the
execution string of /usr/sbin/haveged (which then becomes @usr/sbin/haveged)

Here the haveged opens fd 3

 haveged: listening socket at 3

 ps aux  | grep haveged
 root     29077  6.2  0.0  12168  4824 ?        Ss   14:41   0:00 @usr/sbin/haveged -w 1024 -v 0 -F

and with

 strace -p 29077

and in an other tty

 systemctl start haveged-switch-root.service

I see

 pselect6(7, [3], [6], NULL, {tv_sec=0, tv_nsec=699096618}, {[], 8}) = 0 (Timeout)
 pselect6(7, [3], [6], NULL, {tv_sec=2, tv_nsec=0}, {[], 8}) = 1 (in [3], left {tv_sec=0, tv_nsec=497113957})
 accept4(3, NULL, NULL, SOCK_CLOEXEC|SOCK_NONBLOCK) = 7
 pselect6(8, [3 7], [6], NULL, {tv_sec=2, tv_nsec=0}, {[], 8}) = 1 (in [7], left {tv_sec=1, tv_nsec=999995954})
 ioctl(5, FIONREAD, [12])                = 0
 recvfrom(5, "R\2", 2, MSG_DONTWAIT, NULL, NULL) = 2
 ioctl(5, FIONREAD, [10])                = 0
 recvfrom(5, "\t", 1, MSG_DONTWAIT, NULL, NULL) = 1
 ioctl(5, FIONREAD, [9])                 = 0
 recvfrom(5, "/sysroot\0", 9, MSG_DONTWAIT, NULL, NULL) = 9
 getsockopt(5, SOL_SOCKET, SO_PEERCRED, {pid=29188, uid=0, gid=0}, [12]) = 0
 sendto(5, "\6\0", 2, MSG_NOSIGNAL, NULL, 0) = 2
 write(2, "haveged: restart in new root: /s"..., 39) = 39
 chdir("/sysroot")                       = 0
 chroot(".")                             = 0
 chdir("/")                              = 0
 execve("/usr/sbin/haveged", ["@usr/sbin/haveged", "-w", "1024", "-v", "0", "-F"], 0x7fff12681e60 /* 4 vars */) = 0
 [...]
 openat(AT_FDCWD, "/proc/sys/kernel/random/write_wakeup_threshold", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 7
 fstat(7, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
 write(7, "1024\n", 5)                   = 5
 close(7)                                = 0
 openat(AT_FDCWD, "/dev/random", O_RDWR) = 7
 rt_sigprocmask(SIG_BLOCK, [HUP INT PIPE TERM], [], 8) = 0
 pselect6(8, [3], [7], NULL, {tv_sec=2, tv_nsec=0}, {[], 8} <detached ...>

AFAICS it should also work without /etc/initrd-release if haveged is started in normal
way in foreground (option -F) but without private network by the systemd service unit.
Then a normal haveged -c root=/tmp should work.


Werner

-- 
  "Having a smoking section in a restaurant is like having
          a peeing section in a swimming pool." -- Edward Burr

**Comment by jirka-h** [comment]
I have attempted to create all files under the new root but I don't have /etc/initrd-release file (I'm running Fedora 27)

strace /tmp/A/sbin/haveged -c root=/tmp
shows that this check fails:
access("/etc/initrd-release", F_OK)     = -1 ENOENT (No such file or directory)

Could you please acknowledge that the new functionality works for you? It seems that my artificial testing does not make much sense. 

Could you also please check the other issue with two haveged instances running in the foreground mode?

$haveged -n0 -v3 >/dev/null
$haveged -n0 -v3 >/dev/null

I'm getting:
`haveged: listening socket at -2`

It should return a warning that `Address already in use`:

```
$strace -e trace=\!write /tmp/A/sbin/haveged -n0 -v3 >/dev/null
socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
setsockopt(3, SOL_SOCKET, SO_PASSCRED, [1], 4) = 0
bind(3, {sa_family=AF_UNIX, sun_path=@"/sys/entropy/haveged"}, 23) = -1 EADDRINUSE (Address already in use)
close(3)                                = 0
haveged: listening socket at -2
```
Thanks!
Jirka

**Comment by bitstreamout** [comment]
On Fri, Aug 10, 2018 at 06:44:02AM -0700, jirka-h wrote:
> I have attempted to create all files under the new root but I don't have /etc/initrd-release file (I'm running Fedora 27)
> 
> strace /tmp/A/sbin/haveged -c root=/tmp
> shows that this check fails:
> access("/etc/initrd-release", F_OK)     = -1 ENOENT (No such file or directory)
> 
> Could you please acknowledge that the new functionality works for you? It seems that my artificial testing does not make much sense. 
> 
> Could you also please check the other issue with two haveged instances running in the foreground mode?
> 
> $haveged -n0 -v3 >/dev/null
> $haveged -n0 -v3 >/dev/null
> 
> I'm getting:
> `haveged: listening socket at -2`
> 
> It should return a warning that `Address already in use`:
> 
> ```
> $strace -e trace=\!write /tmp/A/sbin/haveged -n0 -v3 >/dev/null
> socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
> setsockopt(3, SOL_SOCKET, SO_PASSCRED, [1], 4) = 0
> bind(3, {sa_family=AF_UNIX, sun_path=@"/sys/entropy/haveged"}, 23) = -1 EADDRINUSE (Address already in use)
> close(3)                                = 0
> haveged: listening socket at -2
> ```

Aha ... there seems to be already a haveged runing. That cause the your haveged
catches an error with EADDRINUSE.  With this fd is set to -2 in cmd_listen()

It seems that the fprintf() reporting that haveged is listen on fd should
not be done with fd <= 0 ... but a report that there might be an other
instance of haveged is running could be an better idea.

Werner

-- 
  "Having a smoking section in a restaurant is like having
          a peeing section in a swimming pool." -- Edward Burr

**Comment by bitstreamout** [comment]
On Fri, Aug 10, 2018 at 06:44:02AM -0700, jirka-h wrote:
> I have attempted to create all files under the new root but I don't have /etc/initrd-release file (I'm running Fedora 27)
> 
> strace /tmp/A/sbin/haveged -c root=/tmp
> shows that this check fails:
> access("/etc/initrd-release", F_OK)     = -1 ENOENT (No such file or directory)
> 
> Could you please acknowledge that the new functionality works for you? It seems that my artificial testing does not make much sense. 
> 
> Could you also please check the other issue with two haveged instances running in the foreground mode?
> 
> $haveged -n0 -v3 >/dev/null
> $haveged -n0 -v3 >/dev/null
> 
> I'm getting:
> `haveged: listening socket at -2`
> 
> It should return a warning that `Address already in use`:
> 
> ```
> $strace -e trace=\!write /tmp/A/sbin/haveged -n0 -v3 >/dev/null
> socket(AF_UNIX, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
> setsockopt(3, SOL_SOCKET, SO_PASSCRED, [1], 4) = 0
> bind(3, {sa_family=AF_UNIX, sun_path=@"/sys/entropy/haveged"}, 23) = -1 EADDRINUSE (Address already in use)
> close(3)                                = 0
> haveged: listening socket at -2
> ```
> Thanks!
> Jirka

Just build a version based on 1.9.3 and it works perfect

Werner

-- 
  "Having a smoking section in a restaurant is like having
          a peeing section in a swimming pool." -- Edward Burr

**Pull request merged**
